"""Add FK between plannings and occupations

Revision ID: 2c040014f26e
Revises: d89cb979b577
Create Date: 2025-06-05 12:22:33.206508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c040014f26e'
down_revision: Union[str, None] = 'd89cb979b577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupations', sa.Column('planning_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'occupations', 'plannings', ['planning_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'occupations', type_='foreignkey')
    op.drop_column('occupations', 'planning_id')
    # ### end Alembic commands ###
