"""Initial migration

Revision ID: d89cb979b577
Revises: 
Create Date: 2025-06-05 11:57:09.121961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89cb979b577'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('LICENCE', 'MASTER', 'INGENIEUR', 'DOCTORAT', 'BTS', name='cycleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cycles_id'), 'cycles', ['id'], unique=False)
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_filieres_id'), 'filieres', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('READ_USERS', 'WRITE_USERS', 'UPDATE_USERS', 'DELETE_USERS', 'MANAGE_USER_PERMISSIONS', 'UPLOAD_USER_PHOTO', 'READ_ROLES', 'WRITE_ROLES', 'UPDATE_ROLES', 'DELETE_ROLES', 'MANAGE_ROLE_PERMISSIONS', 'READ_PERMISSIONS', 'WRITE_PERMISSIONS', 'UPDATE_PERMISSIONS', 'DELETE_PERMISSIONS', 'LOGIN', 'RESET_PASSWORD', 'CREATE_OTP', 'VERIFY_OTP', 'READ_TEACHERS', 'WRITE_TEACHERS', 'UPDATE_TEACHERS', 'DELETE_TEACHERS', 'MANAGE_TEACHER_DEPARTEMENTS', 'MANAGE_TEACHER_COURS', 'READ_AVAILABILITIES', 'WRITE_AVAILABILITIES', 'UPDATE_AVAILABILITIES', 'DELETE_AVAILABILITIES', 'READ_STUDENTS', 'WRITE_STUDENTS', 'UPDATE_STUDENTS', 'DELETE_STUDENTS', 'READ_SCHOOLS', 'WRITE_SCHOOLS', 'UPDATE_SCHOOLS', 'DELETE_SCHOOLS', 'MANAGE_SCHOOL_TEACHERS', 'READ_DEPARTEMENTS', 'WRITE_DEPARTEMENTS', 'UPDATE_DEPARTEMENTS', 'DELETE_DEPARTEMENTS', 'READ_SECTIONS', 'WRITE_SECTIONS', 'UPDATE_SECTIONS', 'DELETE_SECTIONS', 'MANAGE_SECTION_FILIERES', 'READ_FILIERES', 'WRITE_FILIERES', 'UPDATE_FILIERES', 'DELETE_FILIERES', 'MANAGE_FILIERE_SECTIONS', 'READ_SPECIALITES', 'WRITE_SPECIALITES', 'UPDATE_SPECIALITES', 'DELETE_SPECIALITES', 'MANAGE_SPECIALITE_CYCLES', 'READ_CYCLES', 'WRITE_CYCLES', 'UPDATE_CYCLES', 'DELETE_CYCLES', 'MANAGE_CYCLE_SPECIALITES', 'READ_COURS', 'WRITE_COURS', 'UPDATE_COURS', 'DELETE_COURS', 'READ_CLASSES', 'WRITE_CLASSES', 'UPDATE_CLASSES', 'DELETE_CLASSES', 'MANAGE_CLASSE_COURS', 'READ_SALLES', 'WRITE_SALLES', 'UPDATE_SALLES', 'DELETE_SALLES', 'READ_OCCUPATIONS', 'WRITE_OCCUPATIONS', 'UPDATE_OCCUPATIONS', 'DELETE_OCCUPATIONS', 'READ_RESSOURCES', 'WRITE_RESSOURCES', 'UPDATE_RESSOURCES', 'DELETE_RESSOURCES', 'MANAGE_RESSOURCE_COURS', 'READ_EVENEMENTS', 'WRITE_EVENEMENTS', 'UPDATE_EVENEMENTS', 'DELETE_EVENEMENTS', 'READ_RESERVATIONS', 'WRITE_RESERVATIONS', 'UPDATE_RESERVATIONS', 'DELETE_RESERVATIONS', 'MANAGE_RESERVATION_RESSOURCES', 'GENERATE_PLANNING', 'READ_PLANNING', 'READ_HISTORICAL_PLANNINGS', name='permissionenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_table('plannings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date', name='unique_week')
    )
    op.create_index(op.f('ix_plannings_id'), 'plannings', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'STUDENT', 'TEACHER', 'VISITOR', name='roleenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('salles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type_salle', sa.Enum('SALLE_DE_CLASSE', 'SALLE_INFORMATIQUE', 'SALLE_DE_CONFERENCE', 'SALLE_DE_TP', 'SALLE_DE_REUNION', 'SALLE_DE_SPORT', 'SALLE_DE_MUSIQUE', 'AMPHITHEATRE', 'SALLE_DE_DETENTE', 'BIBLIOTHEQUE', 'SALLE_DE_SIMULATION', name='typesalleenum'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.CheckConstraint('capacity > 0', name='check_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_salles_id'), 'salles', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sigle', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phones', sa.Text(), nullable=False),
    sa.Column('emails', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('establishment_type', sa.Enum('UNIVERSITE_PUBLIQUE', 'UNIVERSITE_PRIVEE', 'UNIVERSITE_INTERNATIONALE', 'UNIVERSITE_TECHNOLOGIQUE', 'UNIVERSITE_POLYTECHNIQUE', 'UNIVERSITE_A_DISTANCE', 'UNIVERSITE_CONFESSIONNELLE', 'INSTITUT_DE_TECHNOLOGIE', 'INSTITUT_DE_FORMATION_PROFESSIONNELLE', 'INSTITUT_DES_SCIENCES_APPLIQUEES', 'INSTITUT_DE_COMMERCE', 'INSTITUT_DE_GESTION', 'INSTITUT_D_AGRICULTURE', 'INSTITUT_D_INFORMATIQUE', 'INSTITUT_DES_SCIENCES_DE_LA_SANTE', 'INSTITUT_DE_TRADUCTION_ET_INTERPRETATION', 'INSTITUT_D_ETUDES_RELIGIEUSES', 'ECOLE_NORMALE_SUPERIEURE', 'ECOLE_NATIONALE_D_ADMINISTRATION', 'ECOLE_NATIONALE_POLYTECHNIQUE', 'ECOLE_DE_COMMERCE', 'ECOLE_D_INGENIEURS', 'ECOLE_DE_JOURNALISME', 'ECOLE_D_ARCHITECTURE', 'ECOLE_D_ART_ET_DE_DESIGN', 'ECOLE_DE_CINEMA_ET_DES_MEDIAS', 'ECOLE_DE_MUSIQUE_ET_DE_DANSE', 'ECOLE_DE_DROIT', 'FACULTE_DE_MEDECINE', 'FACULTE_DE_PHARMACIE', 'ECOLE_DE_SANTE_PUBLIQUE', 'ECOLE_VETERINAIRE', 'ACADEMIE_MILITAIRE', 'CENTRE_DE_FORMATION_PROFESSIONNELLE', 'CENTRE_TECHNOLOGIQUE', 'CENTRE_AGRICOLE', 'CENTRE_DE_FORMATION_MARITIME', 'CENTRE_DE_MAINTENANCE_INDUSTRIELLE', 'COLLEGE_UNIVERSITAIRE', 'ACADEMIE_DES_SCIENCES', 'ACADEMIE_DES_BEUX_ARTS', 'SEMINAIRE_THEOLOGIQUE', 'UNIVERSITE_BILINGUE', 'ETABLISSEMENT_PUBLIC_PRIVE', 'UNIVERSITE_COMMUNAUTAIRE', 'UNIVERSITE_OUVERTE', name='typeetablissement'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logo'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sigle'),
    sa.UniqueConstraint('website')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('departements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_departements_id'), 'departements', ['id'], unique=False)
    op.create_table('evenements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type_evenement', sa.Enum('COURS', 'TD', 'TP', 'EXAMEN', 'SOUTENANCE', 'SEMESTRE', 'RATTRAPAGE', 'CONFÉRENCE', 'REUNION', 'WORKSHOP', 'SEMINAIRE', 'FORMATION', 'WEBINAIRE', 'TABLE_RONDE', 'CULTUREL', 'FESTIVAL', 'SOIREE', 'COCKTAIL', 'GALA', 'MATCH', 'TOURNOI', 'JOURNEE_SPORTIVE', 'STAGE_SPORTIF', 'PARRAINAGE', 'CEREMONIE', 'CAMPAGNE_SENSIBILISATION', 'EXPOSITION', 'FOIRE', 'CONFÉRENCE_WEB', 'INTEGRATION', 'EXAMEN_CC', 'EXAMEN_MEDIAN', 'EXAMEN_SESSION1', 'EXAMEN_SESSION2', name='eventtypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_evenements_id'), 'evenements', ['id'], unique=False)
    op.create_table('ressources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type_ressource', sa.Enum('LIVRE', 'MATERIEL', 'NUMERIQUE', 'FOURNITURE', name='resourcetypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_ressources_id'), 'ressources', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('specialites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specialites_id'), 'specialites', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('specialite_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialite_id'], ['specialites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_table('cours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type_cours', sa.Enum('COURS_MAGISTRAL', 'SEMINAIRE', 'TD', 'TP', 'COURS_EN_LIGNE', 'FORMATION_CONTINUE', 'DEVELOPPEMENT_PERSONNEL', 'CERTIFICATIONS_PROFESSIONNELLES', 'E_LEARNING', 'WEBINAIRE', 'COURS_EN_STREAMING', 'PREPARATION_EXAMEN', 'COURS_PRATIQUES', 'REMISE_A_NIVEAU', 'ALTERNANCE', 'SOUTIEN_SCOLAIRE', 'EVEIL', 'COURS_DE_LANGUES', 'COURS_INTENSIFS', 'BOOTCAMP', 'IMMERSION', 'COURS_PARTICULIERS', 'COACHING', name='typecourenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.Column('specialite_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specialite_id'], ['specialites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cours_id'), 'cours', ['id'], unique=False)
    op.create_table('cycle_specialites',
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('specialite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialite_id'], ['specialites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cycle_id', 'specialite_id')
    )
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_table('school_admins',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_id', 'user_id')
    )
    op.create_table('school_teachers',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_id', 'user_id')
    )
    op.create_table('section_filieres',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'filiere_id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('classe_cours',
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classe_id', 'cours_id')
    )
    op.create_table('cours_ressources',
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('ressource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ressource_id'], ['ressources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cours_id', 'ressource_id')
    )
    op.create_table('occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salle_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('jour', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='weekdayenum'), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupations_id'), 'occupations', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='check_time_order'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_availability_id'), 'teacher_availability', ['id'], unique=False)
    op.create_table('teacher_cours',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'cours_id')
    )
    op.create_table('teacher_departements',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('departement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'departement_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('evenement_id', sa.Integer(), nullable=True),
    sa.Column('salle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', 'EXPIRED', 'IN_PROGRESS', 'WAITLISTED', name='reservationstatusenum'), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salle_id'], ['salles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_table('student_cours_status',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('cours_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INSCRIT', 'EXCLU', 'EXEMPTE', name='studentcoursstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'cours_id')
    )
    op.create_table('reservation_ressources',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('ressource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ressource_id'], ['ressources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reservation_id', 'ressource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation_ressources')
    op.drop_table('student_cours_status')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('teacher_departements')
    op.drop_table('teacher_cours')
    op.drop_index(op.f('ix_teacher_availability_id'), table_name='teacher_availability')
    op.drop_table('teacher_availability')
    op.drop_table('students')
    op.drop_index(op.f('ix_occupations_id'), table_name='occupations')
    op.drop_table('occupations')
    op.drop_table('cours_ressources')
    op.drop_table('classe_cours')
    op.drop_table('user_permissions')
    op.drop_table('teachers')
    op.drop_table('section_filieres')
    op.drop_table('school_teachers')
    op.drop_table('school_admins')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_table('cycle_specialites')
    op.drop_index(op.f('ix_cours_id'), table_name='cours')
    op.drop_table('cours')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_specialites_id'), table_name='specialites')
    op.drop_table('specialites')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_ressources_id'), table_name='ressources')
    op.drop_table('ressources')
    op.drop_index(op.f('ix_evenements_id'), table_name='evenements')
    op.drop_table('evenements')
    op.drop_index(op.f('ix_departements_id'), table_name='departements')
    op.drop_table('departements')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_salles_id'), table_name='salles')
    op.drop_table('salles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_plannings_id'), table_name='plannings')
    op.drop_table('plannings')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_filieres_id'), table_name='filieres')
    op.drop_table('filieres')
    op.drop_index(op.f('ix_cycles_id'), table_name='cycles')
    op.drop_table('cycles')
    # ### end Alembic commands ###
